version: '2'
services:
  postgresql:
    image: 'bitnami/postgresql:11'
    container_name: postgresql
    hostname: postgresql
    environment:
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    restart: always
    
volumes:
  odoo:
    image: 'bitnami/odoo:12'
    container_name: odoo
    hostname: odoo
    ports:
      - '80:8069'
      - '443:8071'
    volumes:
      - 'odoo_data:/bitnami'
    environment:
      - ODOO_EMAIL=odoo@openemail.io
      - ODOO_PASSWORD=odoo@cybergate
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=pgsql@cybergate
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_PORT_NUMBER=5432
      - SMTP_HOST=hasuna.openemail.io
      - SMTP_PORT=465
      - SMTP_USER=odoo@openemail.io
      - SMTP_PASSWORD=odoo@cybergate
      - SMTP_PROTOCOL=ssl
    depends_on:
      - postgresql
    restart: always
volumes:
  postgresql_data:
    driver: local
  odoo_data:
    driver: local
